language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - libboost-dev
      - libeigen3-dev
  homebrew:
    packages:
      - boost
      - eigen
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest --output-on-failure
